### ISSUE TITLE
Error: Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by Rosentti** [YoogottamK/mpris-ytmusic#4]
Happens on line 17 of the addon.

**Comment by Rosentti** [comment]
Fixed by closing and opening youtube music again. A reload doesn't work.

**Comment by Rosentti** [comment]
Nevermind, it's back.

**Comment by yoogottamk** [comment]
Hey!
Were you referring to this?
https://github.com/YoogottamK/mpris-ytmusic/blob/c7baff2e58e4700c737966b2fc31cabf693113a0/background.js#L17

If yes, in that case, it [seems like](https://stackoverflow.com/a/44683772) the content script for youtube music isn't active.

The content script will only run on pages with the URL `*://music.youtube.com/*`
https://github.com/YoogottamK/mpris-ytmusic/blob/c7baff2e58e4700c737966b2fc31cabf693113a0/manifest.json#L10

---

Does doing the following help?
 - Make sure you have the MPRIS side ready `node main.js` (note to self: rename files to have more meaningful names)
 - Load the [youtube music website](https://music.youtube.com/)
 - In a new tab, open `about:addons`
 - Disable and enable this extension

**Comment by Rosentti** [comment]
Huh, disabling and enabling the extension works.

**Comment by Rosentti** [comment]
There is a small problem though, I have to disable and enable the extension every now and then for it to work.
